### ISSUE TITLE
Develop American offshoot of einader-helfen

### ISSUE THREAD

**Issue by DanielKraft** [hochschule-darmstadt/einander-helfen#439]
**Reason (Why?)**
In the future, the site is also to be established on the American market. 

**Solution (What?)**
The current version of einader-helfen is to be converted into an American version.
- [x] **FE:** l18n (seperate german-labels from the html-template) - #497
- [x] **BE:** Implentation of a context switch for German and US content - #484
- [x] **BE:** Develop crawler for [volunteermatch.org](https://www.volunteermatch.org/search/?l=United%20States) - #490
- [x] **BE:** Revise the enhancement process - #484
- [x] **BE & FE:** Customize tags - #490

**Out of scope**

**Relation to other Issues**
- **FE:** #473
- **FE:** #445
- **BE:** #437
- **BE:** #474
- **BE:** #481
- **BE:** #486
- **BE & FE:** #489

**Acceptance criteria**
